version: "3.9"

services:
  leolani:
    image: "numblr/eliza:latest"
    ports:
      - "8000:8000"
    volumes:
      - ./config:/cltl_k8_config
      - ./credentials:/credentials
      - ./storage:/leolani/cltl-leolani-app/py-app/storage
    environment:
      - CLTL_LOGGING_CONFIG=/cltl_k8_config/.logging.config
